CREATE TABLE LANGUAGE (
    ENTITY_ID BIGINT PRIMARY KEY,
    NAME      VARCHAR(128) UNIQUE NOT NULL
) TABLESPACE ${tbsTables};

CREATE SEQUENCE language_sequence;

GRANT SELECT, INSERT, UPDATE, DELETE ON LANGUAGE TO ${appRole};
GRANT SELECT ON LANGUAGE TO ${readerRole};