CREATE SEQUENCE doc_reading_h_sequence;

CREATE TABLE DOCUMENT_READING_HISTORY (
    ENTITY_ID    BIGINT PRIMARY KEY DEFAULT nextval('doc_reading_h_sequence'),
    CLIENT_ID    BIGINT REFERENCES CLIENT(ENTITY_ID) NOT NULL,
    DOCUMENT_ID  BIGINT REFERENCES DOCUMENT(ENTITY_ID) NOT NULL,
    LANGUAGE_ID  BIGINT REFERENCES LANGUAGE(ENTITY_ID) NOT NULL,
    READING_TIME TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC')
) TABLESPACE ${tbsTables};

GRANT SELECT, INSERT, UPDATE, DELETE ON DOCUMENT_READING_HISTORY TO ${appRole};
GRANT SELECT ON DOCUMENT_READING_HISTORY TO ${readerRole};