CREATE TABLE DOCUMENT (
    ENTITY_ID         BIGINT PRIMARY KEY,
    NAME              VARCHAR(128) NOT NULL,
    CLASSIFICATION_ID BIGINT REFERENCES CLASSIFICATION(ENTITY_ID) NOT NULL
) TABLESPACE ${tbsTables};

GRANT SELECT, INSERT, UPDATE, DELETE ON DOCUMENT TO ${appRole};
GRANT SELECT ON DOCUMENT TO ${readerRole};