CREATE TABLE CLASSIFICATION (
    ENTITY_ID BIGINT PRIMARY KEY,
    NAME      VARCHAR(128) NOT NULL
) TABLESPACE ${tbsTables};

CREATE UNIQUE INDEX class_name_idx
    ON CLASSIFICATION (NAME)
    TABLESPACE ${tbsIdx};

CREATE SEQUENCE classification_sequence;

GRANT SELECT, INSERT, UPDATE, DELETE ON CLASSIFICATION TO ${appRole};
GRANT SELECT ON CLASSIFICATION TO ${readerRole};