server:
  port: 8090

spring:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  sql:
    init:
      mode: never
  servlet:
    multipart:
      max-file-size: -1

module-properties:
  mail:
    sender: course.paper.asu@mail.ru
    password: vXX6Aas5ErCy9ndrTVPU
    host: smtp.mail.ru
    port: 465
    protocol: smtps
  jwt:
    secret: ru.gold.ordance
    expirationMs: 1200000
  persistence:
    postgres:
      url: jdbc:postgresql://docs_db:5432/docs
      username: docs
      password: qwe123