server:
  port: 8090

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
      location: ${java.io.tmpdir}

jwt:
  secret: ru.gold.ordance
  expirationMs: 1200000


persistence:
  dialect: POSTGRES

  postgres:
    url: jdbc:postgresql://localhost:5433/docs
    username: docs
    password: qwe123

  h2:
    url: jdbc:h2:mem:docs
    username: h2
    password: