server:
  port: 8090

spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  servlet:
    multipart:
      location: /usr/local/storage
      max-file-size: -1

jwt:
  secret: ru.gold.ordance
  expirationMs: 1200000


persistence:
  postgres:
    url: jdbc:postgresql://docs_db:5432/docs
    username: docs
    password: qwe123