server:
  port: 8090

spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
      location: C:\Users\Кокон\IdeaProjects\course-paper\file

jwt:
  token:
    secret: ru.gold.ordance
    expirationMs: 1200000


persistence:
  dialect: POSTGRES

  postgres:
    url: jdbc:postgresql://localhost:5432/cs
    username: postgres
    password: postgres

  h2:
    url: jdbc:h2:mem:cs
    username: h2
    password: